server:
  port: 8080

spring:

  main:
    web-application-type: reactive
  application:
    name: gateway


  cloud:
    nacos:
      discovery:
        server-addr: 192.168.220.1:8848
      config:
        server-addr: 192.168.220.1:8848
        file-extension: yaml
        group: DEFAULT_GROUP

    gateway:
      routes:
        - id: user
          uri: lb://user-service
          predicates:
            - Path=/users/**,/config/**,/jiaolianxinxi/**,/yuangong/**
        - id: strength
          uri: lb://strength-service
          predicates:
            - Path=/jianshenhuodong/**,/jianshenqicai/**,/jianshenxiangmu/**,/zhidaoxiangmu/**
        - id: member
          uri: lb://member-service
          predicates:
            - Path=/huiyuan/**,/huiyuanka/**,/huiyuankaleixing/**
        - id: file
          uri: lb://file-service
          predicates:
            - Path=/jiepin/**
        - id: redis
          uri: lb://redis-service
          predicates:
            - Path=/redis/**


logging:
  level:
    org.springframework.cloud.gateway: debug

# ✅ 禁用数据库相关配置
# ⚠️ 删除以下内容，如果你不使用数据库：
# mybatis-plus: xxx（全部删除）

